# Preprocessing Demo - placement.csv

**Steps**
1. Load and look
2. Separate numeric and categorical columns
3. Split into X and y
4. Handle missing values
5. Encode categorical columns
6. Scale numeric columns
7. Do 5 and 6 together with ColumnTransformer

**Target shape at the end: (550, 14)**

# Shortened link to group : https://bit.ly/4hc8TmI

---
## Step 1 - Load and look

In [47]:
import numpy as np
import pandas as pd

In [48]:
df=pd.read_csv("/Users/shailesh/Desktop/vedam_Sem3_ml/Data/placement.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   student_id           550 non-null    object
 1   cgpa                 550 non-null    float64
 2   twelfth_percent      550 non-null    float64
 3   branch               550 non-null    object
 4   internships          519 non-null    float64
 5   projects             550 non-null    int64
 6   backlogs             550 non-null    int64
 7   prep_hours           454 non-null    float64
 8   communication_score  538 non-null    float64
 9   hostel               550 non-null    object
 10  placed               550 non-null    object
 11  package_lpa          517 non-null    float64
dtypes: float64(6), int64(2), object(4)
memory usage: 51.7+ KB

In [49]:
df.describe().columns

Index(['cgpa', 'twelfth_percent', 'internships', 'projects', 'backlogs',
       'prep_hours', 'communication_score', 'package_lpa'],
      dtype='object')

---
## Step 2 - Separate numeric and categorical columns

In [50]:
nums_col=['cgpa', 'twelfth_percent', 'internships', 'projects', 'backlogs',
       'prep_hours', 'communication_score']

cat_col=['branch','hostel']

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   student_id           550 non-null    object
 1   cgpa                 550 non-null    float64
 2   twelfth_percent      550 non-null    float64
 3   branch               550 non-null    object
 4   internships          519 non-null    float64
 5   projects             550 non-null    int64
 6   backlogs             550 non-null    int64
 7   prep_hours           454 non-null    float64
 8   communication_score  538 non-null    float64
 9   hostel               550 non-null    object
 10  placed               550 non-null    object
 11  package_lpa          517 non-null    float64
dtypes: float64(6), int64(2), object(4)
memory usage: 51.7+ KB

---
## Step 3 - Split into X and y

In [52]:
x=df.drop(columns=['student_id','placed','package_lpa'])
y=df['placed']

In [53]:
# nums_col=['cgpa', 'twelfth_percent', 'internships', 'projects', 'backlogs',
#        'prep_hours', 'communication_score']

for col in nums_col:
    x[col]=x[col].fillna(x[col].mean())

In [54]:
df.isnull().sum()

student_id              0
cgpa                    0
twelfth_percent         0
branch                  0
internships            31
projects                0
backlogs                0
prep_hours             96
communication_score    12
hostel                  0
placed                  0
package_lpa            33
dtype: int64

---
## Step 4 - Handle missing values

In [55]:
df.isnull().sum()

student_id              0
cgpa                    0
twelfth_percent         0
branch                  0
internships            31
projects                0
backlogs                0
prep_hours             96
communication_score    12
hostel                  0
placed                  0
package_lpa            33
dtype: int64

---
## Step 5 - Encode categorical columns

In [56]:
print(cat_col)

['branch', 'hostel']

In [57]:
df['branch'].value_counts()

branch
CSE      167
IT       118
ECE      112
Mech     103
Civil     50
Name: count, dtype: int64

In [58]:
df['hostel'].value_counts()

hostel
Yes    317
No     233
Name: count, dtype: int64

In [59]:
from sklearn.preprocessing import OneHotEncoder

In [60]:
encoder=OneHotEncoder()

In [61]:
encoded=encoder.fit_transform(x[cat_col])
print((encoded.shape))

(550, 7)

In [62]:
print(x.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   cgpa                 550 non-null    float64
 1   twelfth_percent      550 non-null    float64
 2   branch               550 non-null    object
 3   internships          550 non-null    float64
 4   projects             550 non-null    int64
 5   backlogs             550 non-null    int64
 6   prep_hours           550 non-null    float64
 7   communication_score  550 non-null    float64
 8   hostel               550 non-null    object
dtypes: float64(5), int64(2), object(2)
memory usage: 38.8+ KB
None

In [63]:
print(type(encoded))

<class 'scipy.sparse._csr.csr_matrix'>

In [64]:
encoded_df = pd.DataFrame(encoded.toarray(),
                          columns=encoder.get_feature_names_out(cat_col))
encoded_df.head()

,branch_CSE,branch_Civil,branch_ECE,branch_IT,branch_Mech,hostel_No,hostel_Yes
0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0

---
## Step 6 - Scale numeric columns

In [65]:
from sklearn.preprocessing import StandardScaler

In [66]:
scaler=StandardScaler()
scaled_col=scaler.fit_transform(x[nums_col])
scaled_col.shape

(550, 7)

In [67]:
scaled_df = pd.DataFrame(scaled_col, columns=nums_col)
scaled_df.head()

,cgpa,twelfth_percent,internships,projects,backlogs,prep_hours,communication_score
0,0.052687,0.089252,-1.135637,2.308285,0.288591,0.446204,-1.179898
1,0.164689,-0.751306,0.608137,0.295246,-0.623622,0.177314,2.115353
2,-0.008405,0.069474,0.608137,-1.717794,2.113016,0.587051,-0.880330
3,0.510876,-1.720420,-0.263750,0.295246,-0.623622,-0.232423,1.036907
4,-1.759703,1.058366,0.608137,-0.375767,-0.623622,-0.270836,0.018375

In [68]:
scaled_df.describe().round(2)

,cgpa,twelfth_percent,internships,projects,backlogs,prep_hours,communication_score
count,550.00,550.00,550.00,550.00,550.00,550.00,550.00
mean,0.00,0.00,0.00,-0.00,0.00,-0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-2.40,-2.23,-1.14,-1.72,-0.62,-1.76,-3.10
25%,-0.68,-0.66,-1.14,-1.05,-0.62,-0.67,-0.64
50%,0.04,0.03,-0.26,-0.38,-0.62,0.00,0.02
75%,0.63,0.68,0.61,0.97,0.29,0.31,0.62
max,2.69,2.02,2.35,2.31,3.03,4.44,2.24

In [83]:
df.describe()

,cgpa,twelfth_percent,internships,projects,backlogs,prep_hours,communication_score,package_lpa
count,550.000000,550.000000,519.000000,550.00000,550.000000,454.000000,538.000000,517.000000
mean,7.358255,77.597455,1.302505,2.56000,0.683636,153.151982,6.269331,4.711857
std,0.983022,10.121533,1.181834,1.49164,1.097233,86.055100,1.689150,3.475017
min,5.000000,55.000000,0.000000,0.00000,0.000000,16.000000,1.100000,0.000000
25%,6.690000,70.900000,0.000000,1.00000,0.000000,90.000000,5.200000,0.000000
50%,7.400000,77.900000,1.000000,2.00000,0.000000,134.000000,6.300000,6.010000
75%,7.975000,84.500000,2.000000,4.00000,1.000000,192.750000,7.400000,7.280000
max,10.000000,98.000000,4.000000,6.00000,4.000000,500.000000,10.000000,12.560000

---
## Step 7 - Both together with ColumnTransformer

In [69]:
from sklearn.compose import ColumnTransformer

In [70]:
preprocessor=ColumnTransformer([
    ('cat',OneHotEncoder(),cat_col),
    ('num',StandardScaler(),nums_col)
]
)

In [71]:
final_transform=preprocessor.fit_transform(x)
print(final_transform.shape)

(550, 14)

In [72]:
preprocessor.get_feature_names_out()

array(['cat__branch_CSE', 'cat__branch_Civil', 'cat__branch_ECE',
       'cat__branch_IT', 'cat__branch_Mech', 'cat__hostel_No',
       'cat__hostel_Yes', 'num__cgpa', 'num__twelfth_percent',
       'num__internships', 'num__projects', 'num__backlogs',
       'num__prep_hours', 'num__communication_score'], dtype=object)

In [73]:
final_transform.shape

(550, 14)

In [74]:
df.head(3)

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
0,VS2821,7.41,78.5,IT,0.0,6,1,188.0,4.3,No,No,0.00
1,VS3068,7.52,70.0,CSE,2.0,3,0,167.0,9.8,Yes,Yes,10.06
2,VS2940,7.35,78.3,CSE,2.0,0,3,199.0,4.8,Yes,Yes,NaN

In [75]:
final_df = pd.DataFrame(final_transform,
                        columns=preprocessor.get_feature_names_out())
final_df.head()

,cat__branch_CSE,cat__branch_Civil,cat__branch_ECE,cat__branch_IT,cat__branch_Mech,cat__hostel_No,cat__hostel_Yes,num__cgpa,num__twelfth_percent,num__internships,num__projects,num__backlogs,num__prep_hours,num__communication_score
0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.052687,0.089252,-1.135637,2.308285,0.288591,0.446204,-1.179898
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.164689,-0.751306,0.608137,0.295246,-0.623622,0.177314,2.115353
2,1.0,0.0,0.0,0.0,0.0,0.0,1.0,-0.008405,0.069474,0.608137,-1.717794,2.113016,0.587051,-0.880330
3,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.510876,-1.720420,-0.263750,0.295246,-0.623622,-0.232423,1.036907
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.759703,1.058366,0.608137,-0.375767,-0.623622,-0.270836,0.018375

---
## Step 8 - Train and test split

In [76]:
from sklearn.model_selection import train_test_split

In [77]:
x_train, x_test, y_train, y_test = train_test_split(
    final_transform, y, test_size=0.2, random_state=42)


print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(440, 14)
(110, 14)
(440,)
(110,)

---
## Step 9 - Train the model

In [78]:
from sklearn.neighbors import KNeighborsClassifier

In [79]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(x_train, y_train)

KNeighborsClassifier()

In [80]:
y_pred = model.predict(x_test)
y_pred[:10]

array(['Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
       'Yes'], dtype=object)

---
## Step 10 - Score

In [81]:
from sklearn.metrics import accuracy_score

In [82]:
accuracy_score(y_test, y_pred)

0.8090909090909091